version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/app-laravel"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      composer-dependencies:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/app-laravel"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      npm-dependencies:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      github-actions-dependencies:
        update-types:
          - "minor"
          - "patch"
