@{
    # Excel DateFormats are dependant to the language of the Excel version. 
    # Adapt the format to your Excel version if you want the date to be properly formatted.
    # ExcelDateFormat = '[$-fr-BE]AAAA-MM-JJ;@'
    # ExcelDateFormat = '[$-en-US]YYYY-MM-DD;@'
    ExcelDateFormat = '[$-fr-BE]AAAA-MM-JJ;@'
    Methods = @(
        'Head'
        'Get'
        'Options'
        'Whatever'
    )
    HttpVersions = @(
        '2.0'
        '1.1'
        '1.0'
    )
    IgnoredHeaders = @(
        'Accept-Ranges'
        'Access-Control-Allow-Origin'
        'Age'
        'Allow'
        'Cache-Control'
        'Connection'
        'Content-Length'
        'Content-Security-Policy'
        'Content-Security-Policy-Report-Only'
        'Content-Type'
        'Cross-Origin-Opener-Policy-Report-Only'
        'Date'
        'ETag'
        'Expires'
        'Keep-Alive'
        'Last-Modified'
        'Link'
        'Location'
        'Nel'
        'P3P'
        'Permissions-Policy'
        'Persistent-Auth'
        'Pragma'
        'Public'
        'Referrer-Policy'
        'report-to'
        'Report-To'
        'Reporting-Endpoints'
        'request-id'
        'Set-Cookie'
        'SPRequestGuid'
        'Strict-Transport-Security'
        'Transfer-Encoding'
        'Vary'
        'X-Content-Type-Options'
        'X-Correlation-ID'
        'X-DNS-Prefetch-Control'
        'X-Frame-Options'
        'x-ms-ests-server'
        'x-ms-proxy-app-id'
        'x-ms-proxy-connector-id'
        'x-ms-proxy-connector-id'
        'x-ms-proxy-data-center'
        'x-ms-proxy-error-details'
        'x-ms-proxy-group-id'
        'x-ms-proxy-service-name'
        'x-ms-proxy-subscription-id'
        'x-ms-proxy-transaction-id'
        'x-ms-request-id'
        'x-ms-srs'
        'X-Trace-Id'
        'X-XSS-Protection'
    ) 
}